
# Note: HSX is defined in the environment by the project level Makefile
HSX := hsx

default:
	$(HSX)

options:
	@echo "Example 1: Targets"
	@echo
	@echo "default - Simply run hsx with defaults - shows single file + single tag"

