
info:
	@echo "This directory contains a simple example of an HTML"
	@echo "page which gets fragments injected"
	@echo
	@echo "Targets:"
	@echo "   make all   - creates the result file"
	@echo "   make clean - cleans up and deletes the result file"
	@echo


all:
	hsx --file source-page.html --destfile result-file.html

clean:
	rm -f *~
	rm -f result-file.html
